FROM node:8.12.0

RUN apt update && apt install -y curl
WORKDIR /app

ADD package.json ./
RUN npm install .

ADD .babelrc ./
ADD webpack.config.js ./
ADD web ./web

ENTRYPOINT node_modules/.bin/webpack-dev-server --host 0.0.0.0 --port 8001
